version: '3.8'
services:
  dev:
    container_name: coroutine_context_api
    image: coroutine_context_api
    build: .
    tty: true
    volumes:
      - ./:/var/www
    environment:
      - PHP_IDE_CONFIG=serverName=CoroutineContextAPI
